### PR TITLE
Implemented Testing for ButtonStep, CardStep, ConfidenceScoreCalculat…

### LINKED ISSUE #101: Implement Full Coverage Testing for ConfidenceScoreOptimizer, ConfidenceScoreCalculator, ButtonStep, CardStep

### PR DESCRIPTION
**Pull request by auroraborie**
amended ConfidenceScoreOptimizer to return the ranked talksteps by their confidence score in decreasing order as an ArrayList of Maps. Made the corresponding changes to WozWozTranscriptAnalysisInteractor to be compatible with these changes so that the same functionality remains.

-A capping feature was implemented on ConfidenceScoreCalculator so no percentages exceeding greater than 100 was returned
-ConfidenceScoreCalculator also now rounds the confidence score to 2 decimal places.

Notes for the Testing:
-full coverage testing for every line for the entities ButtonStep, CardStep, ConfidenceScoreOptimizer, ConfidenceScoreCalculator
This was done with a variety of dialogues suitable for specific TalkSteps to demonstrate suitability.
-max scores for ButtonStep and CardStep were amended to provide more accurate results

### CODE REVIEW

**Comment by edwardhuahan** [comment]
Good work, but next time there is a merge, make sure to merge all the changes properly and push especially if there is an error

**Comment by edwardhuahan** [comment]
Also- you don't need to make a new PR since if you commit and push to your old branch it will auto-update that PR. Make sure to delete your old one since that one is now obsolete.

**Comment by edwardhuahan** [comment]
Great job, I like the fixes and especially how the rounding error is gone now. Great work on the tests they're very thorough

**Review by edwardhuahan — APPROVED** [review]
^ As mentioned above

**Comment by auroraborie** [comment]
> Also- you don't need to make a new PR since if you commit and push to your old branch it will auto-update that PR. Make sure to delete your old one since that one is now obsolete.

ok Edward thanks for dropping the knowledge! I do try to keep pushing on the same branch but I had troubles merging the pulls so I just created a new branch. In the future I will make sure to delete my old PRs once I make new ones.

**Review by nm-le — APPROVED** [review]

**Pull request merged**
