### PR TITLE
58 Implement use case interactor, scorable interface, and change dialogue and speech entities 

### LINKED ISSUE #58: Use Case Interactor Part One: Implement Use Case Interactor version 1 without the functionality to access the parsed transcript

### PR DESCRIPTION
**Pull request by ZZBP**
Changed Dialogue's attributes: confidenceScore, and setSuggestion to Arraylists to allow us to suggestion the top three steps. Implemented the Scorable interface.  Updated Speech object based on the new data structure. 

Implemented the use case interactor which generates all entities, goes in the parsed transcript, calls suggestionManager, stepManager to eventually store the suggested step with the confidence score in the Dialogue Object.

### CODE REVIEW

**Comment by ZZBP** [comment]
Pushed more files than wanted.

**Comment by edwardhuahan** [comment]
Is there a reason why this pull request is failing the Java check? Does it compile on your end?

**Comment by Lemiex** [comment]
To address Edward's question of why the java test is failing, I believe it's because Zoey's code depends on things like "ImageStep, ButtonStep, ChoiceStep, ... most the Step entities" to be defined already. But they are not because I'm implementing ChoiceStep and CarouselStep and Rory is doing ButtonStep, and Rory and I haven't merged our implementations of those yet so it's not available to Zoey. So when Zoey's code calls ChoiceStep, ButtonStep, etc, it says something like:

`Error:  /home/runner/work/tli-speakfluid/tli-speakfluid/backend/src/main/java/com/speakfluid/backend/usecases/StepSuggestionInteractor.java:[28,5] cannot access com.speakfluid.backend.entities.ChoiceStep`

How can we resolve this? Since we're all implementing things that depend on things other people are implementing, we might always have the Java error in our PR.  
We could just merge this PR with errors... and then when everyone merges their implementations there technically will not be an error anymore since everything is implemented.
OR 
we could Merge the files that are "depended on" the most that don't depend on other things (such as TalkStep) so that can reduce some of the errors in these PRs. BUT there are still some files that depend on other files "of the same level" and need to be merged/implemented at the same time or there will always be these errors

**Comment by ZZBP** [comment]
We are all assigned to certain parts of entities and use case layers. However, in order for the codes to compile locally and efficiency work on the project, we all tentatively implemented some other classes which are not under our responsibility. Thus, when we make a pull request, we will have both the wanted and unwanted files uploaded.

To resolve the addressed problem, we decided to reorganize the order of pull requests and merges. Following is the order:
TalkStep, StepManager, SuggesitonMangaer, and Scorable are the only four files that should have a pr and get merged so everyone can pull and have the same version. 

After we merge those files, I will pull and redo a pull request for the use case interaction.

**Pull request closed without merging**
