### PR TITLE
Refactor Message.java, add WozMessage.java, and WozTranscriptParse.java

### LINKED ISSUE #73: Implement Transcript Parsing

### PR DESCRIPTION
**Pull request by nm-le**
Major changes:

1. Add parse method into WozTranscriptParse.java, awaiting Kai's instructions to integrate method into TranscriptController. The method right now takes in a String file_path and output the required transcript structure of ArrayList<HashMap<String, ArrayList<Dialogue>>>. Details of implementation can be found in docstrings of method. Documentation on how to iterate through a transcript can be found in psvm of the class.
2. Speech.java was renamed to Message.java, and is now an abstract class instead of public. WozMessage extends Message and includes trace_type and message.
3. Since timestamp is not available in the multiwoz dataset, timestamp was deleted from the original Speech.java (now Message.java). Methods using this variable has been commented out.

### CODE REVIEW

**Review by ZZBP — CHANGES_REQUESTED** [review]
Hi Minh! Thank you so much for this huge pr! The documentation is clear and easy to follow! 
I think it is a good idea to rename Speech objects to Message and make it an abstract class. It enables our project to be more flexible with the types of the input data. I just have a few quick questions:

1. I wonder if we should keep the chatBotMessage attribute in Dialogue as `ArrayList<Message>` instead of `ArrayList<WozMessage>`. I am just thinking about what happens when we decide to extend another type of Message. Do we change the Dialogue object again? Or Should we make the Dialogue object an abstract class and extend one WozDialogue? Let me know what you think and if we decide to make the Dialogue object abstract, I can get on that! It will be a quick fix.  
2. When the step entity accesses each message in `runAnalysis `method, should the type be Message instead of WozMessage since it's more general?

**Review by Lemiex — COMMENTED** [review]
Great job on getting the parser to work minh!!

Questions/Comments:
1. Would it make more sense for WozTranscriptParse to be calledWozTranscriptParse**r**?? Not sure about that let me know what you think
2. I noticed in WozTranscriptParse line150, `to_parse.parseTranscript("/Users/minhle/Documents/2nd Year/TLI/tli-speakfluid/data.json");` Are we going to pass in the uploaded transcript in the future? Is this just temporary? What would we change it to?

**Comment by nm-le** [comment]
@ZZBP Thank you for review! If you need any other explanation of my code let me know. About the changes to Dialogue, yes that is actually a good idea. We already abstractified Message and should do that for Dialogue too. I can implement the changes in Dialogue and create WozDialogue, because I need to make sure my parser still works lol.

**Comment by nm-le** [comment]
@Lemiex
1. I think that is a good idea too, although let me check me with Kai on how to properly place the method into backend.

2. It is definitely just temporary and I should have commented it out. That whole psvm is just temporary and I only wrote it there to show you guys how to iterate through the parsed transcript. If you guys want to test it out locally on your computer, you would need to copy the multiwoz json file into the tli-speakfluid folder and replace "/Users/minhle/Documents/2nd Year/TLI/tli-speakfluid/data.json" with the path of that json file (just right-click on the file and select copy path).

Like you said, in the future we will pass in the uploaded file into that function. I am not sure how to do that yet so will need to ask Kai on how to use my method in TranscriptController. @zhg-kj it would be great if you can comment on it here :)

**Review by Lemiex — APPROVED** [review]

**Review by zhg-kj — CHANGES_REQUESTED** [review]
Great job with everything! I have a few concerns which will also address the questions in your reply to Sarah's review.

1. I agree with Sarah, change the name to WozTranscriptParser.java.
2. The function parseTranscript should take in a MultipartFile type instead of the transcript_path. This will be the transcript itself. If you take a look at TranscriptController the "/upload" request at line 24 requests a MultipartFile as part of the API call. We want to directly pass this raw file into the parseTranscript function. Here is what the code should look like for parseTranscript usage:

```
@PostMapping("/upload")
    public ResponseEntity<?> upload(@RequestParam("transcript")MultipartFile transcript) throws IOException {
        // This uploads the raw transcript to the DB and stores the id of the raw transcript in reponse.
        String response = new ResponseEntity<>(transcriptService.addTranscript(transcript), HttpStatus.OK)
        
        // Transcript here is of type MultipartFile and is coming directly from the @RequestParam.
        ArrayList<HashMap<String, ArrayList<Dialogue>>> parsedTranscript = parseTranscript(transcript)

        // Code to classify the talksteps on parsedTranscript will be here.
        return parsedTranscript;
    }
```

**Review by ZZBP — APPROVED** [review]
Amazing work! Thank you for all the changes! Just a quick question what does the parseTranscriptFilePath method in WozTranscriptParser do?

**Review by zhg-kj — APPROVED** [review]

**Comment by nm-le** [comment]
> Amazing work! Thank you for all the changes! Just a quick question what does the parseTranscriptFilePath method in WozTranscriptParser do?

parseTranscriptFilePath takes in a String file_path that you can use to test with a local file. parseTranscript takes in a MultipartFile (uploaded file)

**Pull request merged**
