### PR TITLE
48 create and implement talkstep abstract class

### LINKED ISSUE #48: Create and implement TalkStep abstract class
variables: 
- String stepName
- int scoreAccumulator
- int maxSore

methods: that are common to all Step entities
- calculateSpeechLength(Speech speech)
- matchKeyword(Speech speech)
- i sShortAnswer(Speech speech)
- isFastResponse(Speech speech)

### PR DESCRIPTION
**Pull request by Lemiex**
Note-worthy changes:
- implemented all the public methods in the abstract class
- getMaxScore() and getScoreAccumulator() is for the StepManager to calculate the confidence scre
- setScoreAccumulator is for assignment to the variable at the end of an analysis

Note: 
- calculateResponseTime uses LocalDateTime obejcts for time stamps to match with Speech's speech.timestamp object, which is also a LocalDateTime object
- there is no setMaxScore() because the maxScore is a pre-defined final constant for every Step entity.

### CODE REVIEW

**Comment by ZZBP** [comment]
The documentation for the countMatchKeywords method should be changed. It is currently the same as the calculateResponseTime method.

**Review by zhg-kj — COMMENTED** [review]
Great work Sarah! Love the documentation.

**Review by ZZBP — APPROVED** [review]
Great work! Thank you~~~

**Review by ZZBP — CHANGES_REQUESTED** [review]
Great Work! Could you make some small changes to the TalkStep abstract class? 
Love the clear documentation! I think you accidentally committed all your files though. 

Instance Variables:
- The scoreAccumulator would be different and changed in every child class of TalkStep. Therefore, it should not be a static variable. 
- Add a private String variable called stepName so we can access and return the name of the suggested step in suggestionManager thus the use case interacts. 
    - Make a getter function for stepName as well!
- Like what you have for the getter functions for maxScore and scoreAccumulator.
- Make the setZeroScoreAccumulator non-static since the scoreAccumulator will no longer be static.

Methods:
- I appreciate all the clear documentation for each of the method! 
- Change calculateMsgLength, countMatchKeywords
    - As we decide to store keywords in the format of Map<String, Double>, could you change all the type of the parameter keywords from List<String> to Map<String, Double>?
- Add documentation for the abstract class runAnalysis.

**Comment by Lemiex** [comment]
committed files otehr than TalkStep that I don't want onto the PR. I will close this and open a new one with the right files I want merged the to main branch

**Pull request closed without merging**
