### PR TITLE
implemented ButtonStep, CardStep, StepManager, and SuggestionManager in compliance with our CRC card designs.

### PR DESCRIPTION
**Pull request by auroraborie**
Role in our program: In accordance with our clean architecture design, the SuggestionManager calls the StepManager to return the confidence score of each TalkStep. It will then return a HashMap between the suggested talk step with the highest confidence score and the corresponding confidence score.

The ButtonStep and CardStep are children of the TalkStep abstract class and will inherit common metrics for calculating their suitability of using this step in the dialogue.

Code Notes:

the maxScore attribute is specific to each child of TalkStep as there are a differing number of possible scores each step based on the number of metrics used.
the keyword lists contain scores from highest to lowest which allows for the most likely phrases to be found first, and minimizing the runtime.
the final confidence score will be stored as a double to allow for accuracy through decimal digits.

### CODE REVIEW

**Review by Lemiex — CHANGES_REQUESTED** [review]
Thanks for the huge PR rory! And i appreciate your clean architecture comment.
I focused on reviewing the step entities:
ButtonStep:
1.  Where did the constructor go? it should be public ButtonStep(){ this.scoreAccumulator = 0;}
2. Please change stepName to "Button" so it is consistent with the rest of the step entities
3.  We did say weights and maxScores are TBD after discussion, but i'd still like to comment that maybe some weights could be larger. Such as "Would you" "What type" "What kind" are pretty strong! May deserve a 5 or 4.
4. What are the public chatbotMsgLength and userMsgLength for? Why are they not private like in CardStep?
5. On line 58, we might not want to subtract scores: what if a dialogue didn't pass any tests and also failed this ratio test, and has negative confidence? We can just have the else branch and add points.

CardStep:
1. Why is this scoreAccumulator  `private Double scoreAccumulator;` not `private double scoreAccumulator;` ?
2. Change stepName to "Card"
3. Add a constructor 
4. I realised this also applies to ButtonStep, but if chatbotMsgLength/userMsgLength = calculateMsgLength(speech);, then this will only be the length of the LAST user/chatbot message. So maybe the if statement for the message lengths/ratios can be inside the forloop so it evaluates the lengths for every message in Dialogue
5. For CardStep, you didn't assign  calculateMsgLength(speech); to chatbotMsgLength or userMsgLength on line 45 and line 50

**Comment by edwardhuahan** [comment]
Looks great, I'm just wondering are these different from Use Case Interactors? Is there a reason they're called managers?

**Comment by edwardhuahan** [comment]
Just a note, you don't have to create new branches and pull requests for every requested change Aurora if you push to your original branch that you used to make the PR, it'll auto-update that PR

**Review by ZZBP — CHANGES_REQUESTED** [review]
Hi Aurora! Amazing Work! Basically, Sarah has covered what I want to say about the two-step entities. 

Everything looks great for the StepManager and SuggestionManager just a small note for StepManager: in the method `passDialogueToTalkStep`, remember to add `step.setZeroScoreAccumulator();` since it makes sure our score accumulator will eventually be reset to 0.

**Comment by auroraborie** [comment]
Hey Sarah thank you for the useful notes! I understand the importance of adhering to a convention in our code and though the compiler will run the same way, I realize when I write something it should be following rules that make it easier for others to read. 

For CardStep and ButtonStep, because I moved the if checks within each for loop as you suggested because I think calculating solely based on the length of the speech object is fine for now. Originally I had it outside because I needed to access both the chatbotMsg length and userMsgLength attributes to calculate the ratio. However I believe this is currently unneeded as a metric. 

Due to these changes, I have updated the maxScore attribute accordingly as there will be more opportunities to increate the cumulative score. 

If you have any more questions or comments, let me know :)

**Comment by auroraborie** [comment]
Hey Zoey, thanks for that input! I changed it now :)

**Comment by auroraborie** [comment]
Hi Edward, 
Thanks for the input on the pull requests. I did know that my PRs for my old branches would update when I pushed from them but there were some issues about pushing so I just made a new one. In the future though, I will stick to the same branch for my PRs.

To answer your question, they are called managers because they control the entities needed for calculating the suitability of each talk step for a line of dialogue. Thus, managing these entities. SuggestionManager and StepManager essentially subdivide this task of calculating and returning the talk step with the highest confidence score to follow the Single Responsibility Principal in a clean architecture implementation. SuggestionManager is called by use case interactor though, to divide up the computation and essentially create only one reason why something has to change. 

Hope this helps! :)

**Review by Lemiex — APPROVED** [review]
Looking good!

**Review by ZZBP — APPROVED** [review]
Great Work

**Pull request merged**
