### PR TITLE
Changed countMatchKeywords() return total weighting of matched keywords

### LINKED ISSUE #94: Change countMatchKeywords in TalkStep

### PR DESCRIPTION
**Pull request by Lemiex**
made countMatchKeywords() return total weighting of matched keywords
- implemented change for Choice and Carousel step

### CODE REVIEW

**Review by ZZBP — APPROVED** [review]
Amazing work! Thank you Sarah!

**Review by auroraborie — COMMENTED** [review]
Hi Sarah, could you explain the totalMatchWeighting attribute that you decided to incorporate? What will this do in terms of calculating the confidence score of each talk step? Thanks for the clarification

**Comment by Lemiex** [comment]
Hey Rory, after you proposed to get rid of the 'break' feature in countMatchKeywords(), I made the change to the method in TalkStep to make it happen. The totalMatchWeighting basically does what originally the scoreAccumulator was doing -- adding up all the weights of the keywords that matched the message. After adding up all the weightings of keywords that matched (without break), it returns it as an int, where in the runAnalysis methods of each step entity, will add to the scoreAccumulator. 

Let me know if you have any other questions

**Review by auroraborie — APPROVED** [review]
got it thanks!

**Pull request merged**
