### PR TITLE
Implemented CarouselStep, ImageStep, TextStep, Scorable Entities and Updated Dialogue and Speech

### LINKED ISSUE #53: Implement Text, Image,  Carousel  Entities

### PR DESCRIPTION
**Pull request by ZZBP**
Renamed CalculateConfidenceScre to Scorable.
Implemented Scorable interface.
Implemented CarouselStep,ImageStep,TextStep entities.

Made changes to Dialogue and Speech based on the new data structure:
deleting the no longer needed attributes in Speech. Now the Speech object has only two attributes:
`    private LocalDateTime timeStamp;
    private String message;`

change the type of confidenceScore in Dialogue. Now the Dialogue object has the following attributes:
`    private ArrayList<Speech> chatBotMessage;
    private ArrayList<Speech> userMessage;
    private String stepSuggestion;
    private double confidenceScore;`

### CODE REVIEW

**Review by Lemiex — CHANGES_REQUESTED** [review]
Thanks for the huge PR Zoey, amazing work!!!!
Changes to implement:
1. For each keywords list, make sure to order the words by their weighting -- high to low. That is because the for loop breaks at the first match of a keyword and we want to make sure that one has the largest weighting so can be added to scoreAccumulator.
for example.` Map.ofEntries(entry("map", 1.0), entry("location", 1.0),entry("direction", 1.0), entry("here are", 2.0)),` should be ` Map.ofEntries(entry("here are", 2.0),entry("map", 1.0), entry("location", 1.0),entry("direction", 1.0)),`
2. For CarouselStep, line 35, "here are a list of" with 2.0 weight, should be weighed more than "list of", which has 5.0. The former is longer, more detailed, hence should weight more. You could reverse the two weightings if you think that's reasonable
3. In Carousel Step, Line 36, what does the entry with the empty string mean? If nothing was said? If so, I tried it out and the compiler and turns out it's vacuously true HAHAH did not think a CSC236 concept would be applicable here. (For example, "abc".contains("") return true). So we might wanna take that one out. 
4. Carousel step line 36, "image", "illustration" is repeated. If you're down too, we could delete the whole last Map entry and if you want to keep "choose form the following", you can add it to an earlier Map. With the above changes, you may want to change the maxScore too
5. runAnalysis(), you can combine the bodies of the two for loops since they have the same loop signature. this applies for all your step entity implementations


Notes / Questions
1. Could you briefly comment on the deleted CalculateConfidenceScore file? What was it for and why is it deleted? it seems to have some connection to Scorable -- was it renamed to Scorable?
2. Nice decision making on the weightings -- they mostly seem reasonable to me!
3. We could include some carouselKeyWords if any come to mind! 
4. When you change the document version in the documentation, make sure to change the date as well!
5. For Text step, you could also create a userKeywords, where they are also things along the lines of (Hello, thanks, thx, bye) because they signal that it is the start or end of the conversation and hence our chatbot is probably saying something like "Thanks good bye!" as well, so TextStep is recommended. 
6. For textstep, you can also include things like "rate", "how did I do", "tell me how i did" for chatbot keywords
7. For TextStep, why is numConsecutives = botMsgLength - userMsgLength? Shoudln't it just be numConsecutives = botMsgLength
8. For textstep, line 85, `if (calculateMsgLength(message) >= 15) `, 15 for a sentence seems to be a bit too large for me. My reasoning is chatbots usually know that ppl have short attention spans and wouldn't say too much at once (they may split it into two or more messages). I think around 10-12 might be safe, but its still up to you!

Everything else is splotless. Well done!

**Review by auroraborie — CHANGES_REQUESTED** [review]
Hey Zoey, 

I just reviewed your PR and I think your implementation of the entities adheres very accurately to our design! Also I really am impressed by your documentation, it is very thorough and helps the viewer understand your code.

Just a few notes:
1. In the lists of dictionaries which make up the captureKeyWordsChatbot and captureKeyWordsUsers attributes, I saw that within each mapping phrases were weighted differently. I believe because each mapping is a keyword cluster that are just variations of the same intent, they should be weighted the same. For example, in CaptureStep the first mapping has "please provide" weighted at 5.0 while "provide your" is weighted at 4.0. However because they share the same intent, I think it would make more sense for them to have the same weight. Also this way, when we break out of the loop for the mapping, we know the rest of the entries all are the same score so this does not affect our accumulated score. 
2. I also mentioned this in Sarah's PR but we may need to discuss the max score and the weightings for the keyword mapping further. Could you justify why maxScore here is set to 25? 

Good work on all this code! This is a huge commit and I am so proud of the work you have done for our team!

**Review by Lemiex — APPROVED** [review]
amazing work

**Comment by ZZBP** [comment]
Hey Sarah, thank you so so much for the throughout review! 

1. Make sense! I have changed according! 
2. Yep, thanks for catching that error! Fixed!
3&4. Great points. I think I accidentally just had an extra repetitive line there... made adjustments to that as well. 
5. You are absolutely correct! As I wrote this, I was kind of getting worry as I wrote the same structure for the thrid time.

To answer your questions:
1. Yes, CalculateConfidenceScore is renamed to Scorable since it's an interface and CalculateConfidenceScore sounded like a method. I have added this to the pr description. Sorry about the confusion!
2. Amazing idea for adding user keywords for the Text step that will certainly increase the accuracy of the analysis.
3. As to the reason why I initially chose 15 as the length I searched "average length of a statement," and it gave me 15 words as the standard. However, since we are dealing with chatbots, 10 would be a better fit.  

Again, thank you for the great notes!!!!

**Comment by ZZBP** [comment]
Hi Rory!
I totally understand your point about the keyword attribute. I think there are both pros and cons to the two design ideas we have.  Having different scores will give us a somewhat more accurate analysis. For example, "thanks for contacting" will have a higher score for Text than "thanks"  since it's a better indicator. Being in the same group, if a sentence has "thanks for contacting" then it would have "thanks" so we don't want to count it twice. 

This is definitely worth further discussion. Let me know what you think!

**Review by nm-le — APPROVED** [review]

**Review by auroraborie — APPROVED** [review]

**Pull request merged**
